name: Angular app deployment
on: 
  push:
    branches: 
      - sample
  pull_request:
    branches: 
      - sample
jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm test   
    - name: 'Deploy to Azure Web App'
      uses: actions/webapps-deploy@v2
      with:
        app name: 'hello-world-app-to-delete'
        publish-profile: $
        package: ./dist/hello-world-app
      env:
        CI: true
