name: CI/CD


on: [push]

jobs:
   
   build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.15.1
      uses: actions/setup-node@v1
      with:
        node-version: 8.15.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: test
        branch folder: ${FOLDER}
        build-script: ${BUILD_SCRIPT}        
    
       

 #deploy:
    #needs: build    
    #steps:
      #- name: Checkout
        #uses: actions/checkout@v3
        #with:
          #branch: releases/v4
          #folder: .
          #clean: false
          #single-commit: true
