name: Angular-DEV-CI-CD

on:
  push:
    branches:
      - master
      - develop
      - nehakatam-patch-1
      
      
env:
  AZURE_WEBAPP_NAME: henryscheinuspoc
  AZURE_WEBAPP_PACKAGE_PATH: './dist'
  OUTPUT_FOLDER_PATH: './output'
  ANGULAR_APP_NAME: 'hello-world-app'
  NODE_VERSION: '14.x'
  
jobs:
  ci:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install Dependencies
        #if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm install
          
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
    # Required mail server address:
          server_address: gsmtp.gmail.com
    # Required mail server port:
          server_port: 25
    # Optional (recommended): mail server username:
          username: ${{secrets.EMAIL_USERNAME}}
    # Optional (recommended) mail server password:
          password: ${{secrets.EMAIL_PASSWORD}}
    # Required mail subject:
          subject: Github Actions job result
    # Required recipients' addresses:
          to: neha.katam@henryschein.com
    # Required sender full name (address can be skipped):
          from: Neha Katam # <user@example.com>
    # Optional whether this connection use TLS (default is true if server_port is 465)
          #secure: true
    # Optional plain body:
          #body: Build job of ${{github.repository}} completed successfully!
    # Optional HTML body read from file:
          #html_body: file://README.html
    # Optional carbon copy recipients:
          #cc: kyloren@example.com,leia@example.com
    # Optional blind carbon copy recipients:
          #bcc: r2d2@example.com,hansolo@example.com
    # Optional recipient of the email response:
          #reply_to: luke@example.com
    # Optional Message ID this message is replying to:
          #in_reply_to: <random-luke@example.com>
    # Optional unsigned/invalid certificates allowance:
          #ignore_cert: true
    # Optional converting Markdown to HTML (set content_type to text/html too):
          #convert_markdown: true
    # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/*.js
    # Optional priority: 'high', 'normal' (default) or 'low'
          #priority: low
          
      - name: Build
        run: |
          npm run build
          
      - name: Create the folder for deployment
        run: |
          mkdir ${{ env.OUTPUT_FOLDER_PATH }}
          cp -R ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} ${{ env.OUTPUT_FOLDER_PATH }}/${{ env.ANGULAR_APP_NAME }}/
          rm -r ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/*
          mkdir ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          cp -R ${{ env.OUTPUT_FOLDER_PATH }}/${{ env.ANGULAR_APP_NAME }} ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.ANGULAR_APP_NAME }}/
          
          
 #     - name: 'Deploy to Azure WebApp'
 #       id: deploy-to-webapp 
 #       uses: azure/webapps-deploy@v2
 #       with:
 #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
 #         publish-profile: ${{ secrets.AZURE_ANGULAR_POC_CREDENTIALS }}
 #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
