name: CI/CD


on: [push]

jobs:
   
   build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.15.1
      uses: actions/setup-node@v1
      with:
        node-version: 8.15.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: test
        FOLDER: dist/github-community-sl
        BUILD_SCRIPT: npm install && npm run build -- --prod
        
    - name: Send mail        
      uses: dawidd6/action-send-mail@v3
      with:
         if: ${{success() || failure()}}
         server_address : [smtp.henryschein.com]
    # Required mail server port:
         server_port: 465
    # Optional (recommended): mail server username:
         username: ${{secrets.EMAIL_USERNAME}}
    # Optional (recommended) mail server password:
         password: ${{secrets.EMAIL_PASSWORD}}
    # Required mail subject:
         subject: Github Actions job result
    # Required recipients' addresses:
         to: shanmukha.kandula@henryschein.com
    # Required sender full name (address can be skipped):
         from: Neha Katam # <user@example.com>
    # Optional whether this connection use TLS (default is true if server_port is 465)
         secure: true
    # Optional plain body:
         body: Build job of ${{github.repository}} completed successfully!
       

 #deploy:
    #needs: build    
    #steps:
      #- name: Checkout
        #uses: actions/checkout@v3
        #with:
          #branch: releases/v4
          #folder: .
          #clean: false
          #single-commit: true
