name: Build and deploy node.js app to Azure Web App - hello-world-app-to-delete

on: 
  push:
    branches: 
      - sample
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@sample
    
    - name: setup Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: npm install,build, and test
      run:  
    - run: npm install
    - run: npm run build
    - run: npm test   
    
    - name: 'Deploy to Azure Web App'
      uses: actions/webapps-deploy@v2
      with:
        app name: 'hello-world-app-to-delete'
        publish-profile: $
        package: ./dist/hello-world-app
      env:
        CI: true
